[project]
name = "dotfiles"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gdown>=5.2.0",
    "inquirer>=3.4.0",
    "loguru>=0.7.3",
]

[dependency-groups]
dev = [
    "ruff>=0.8.4",
]
